### ISSUE TITLE
ABOUT BIGINTEGER VALUE

### ISSUE THREAD

**Issue by bill32767** [rachitiitr/DataStructures-Algorithms#11]
Hello sir, thank you so much for your wonderful videos on youtube but I still need help. If the Biginteger value of 63 is 49, 127 is 76, 255 is 224, 511 is 467,  1023 is 514, 2047 is 1155, please what then is the Biginteger value of 2047, 4095, 144115188075855871 and 288230376151711743? Maybe you can help me with a code/formula to do the maths as I don't get the sequence..... Thanks.﻿

**Comment by rachitiitr** [comment]
This is not the portal to ask questions.
